version: '3'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    volumes:
      - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro #Elastic config
      - ./healthcheck/healthcheck:/usr/local/bin/healthcheck:ro #Healthcheck script
      - ./tls/elasticsearch/elasticsearch.p12:/usr/share/elasticsearch/config/elasticsearch.p12:ro #Elastic TCP cert
      - ./tls/elasticsearch/http.p12:/usr/share/elasticsearch/config/http.p12:ro #Elastic HTTP cert
      - data:/usr/share/elasticsearch/data #Elastic data
    ports:
      - "9200:9200" #Elastic HTTP
      - "9300:9300" #Elastic TCP
    environment:
      ES_JAVA_OPTS: "-Xmx4g -Xms4g -Des.enforce.bootstrap.checks=true" #Set JAVA Heap, force selfcheck on start
      discovery.type: single-node #Use only single node
      bootstrap.memory_lock: "true"
    healthcheck:
      test: ["CMD", "healthcheck", "elastic"]
      interval: 1m
    networks:
      - network
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 200000
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro #Kibana config
      - ./healthcheck/healthcheck:/usr/local/bin/healthcheck:ro #Healthcheck script
      - ./tls/kibana/elasticsearch-ca.pem:/usr/share/kibana/config/elasticsearch-ca.pem:ro #Elastic CA
      # - ./tls/kibana/kibana.csr:/usr/share/kibana/config/kibana.csr:ro # Kibana CRT
      # - ./tls/kibana/kibana.key:/usr/share/kibana/config/kibana.key:ro # Kibana CRT Key
    ports:
      - "5601:5601" #Kibana HTTP
    healthcheck:
      test: ["CMD", "healthcheck", "kibana"]
      interval: 1m
    networks:
      - network
    depends_on:
      - elastic
    restart: unless-stopped

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.2
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro #Logstash config
      - ./healthcheck/healthcheck:/usr/local/bin/healthcheck:ro #Healthcheck script
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro #Logstash pipelines config
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro #Logstash pipelines dir. WARNING: each pipeline should be set in config.
      - ./tls/kibana/elasticsearch-ca.pem:/usr/share/logstash/config/elasticsearch-ca.pem:ro #Elastic CA
    ports:
      - "5044:5044" #Logstash Beats input | TCP
      - "9600:9600" #Logstash monitoring
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m" #Set JAVA Heap
    healthcheck:
      test: ["CMD", "healthcheck", "logstash"]
      interval: 1m
    networks:
      - network
    depends_on:
      - elastic
    restart: unless-stopped



volumes:
  data:

networks:
  network:
    driver: bridge
