filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

  processors:
  - decode_json_fields:
      fields: ["message"]
      target: "msg"
      overwrite_keys: true
      add_error_key: false
      when:
        not.has_fields: event.dataset # Do not process applications that will be processed by other modules

  - drop_fields:
      when:
        has_fields: ["msg"]
      fields: ["message"]
      ignore_missing: true

  - drop_fields:
      fields:
        - "agent.ephemeral_id"
        - "docker.container.labels"
        - "msg.@timestamp"
      ignore_missing: true


output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  index: logs-elastic-internal
  ssl.ca_trusted_fingerprint: '${ELASTICSEARCH_CA_FINGERPRINT:}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

# Disable index setup
setup:
  kibana.host: kibana:5601
  dashboards.enabled: false
  dashboards.index: logs-elastic-internal

  template.enabled: false
  template.name: logs
  template.pattern: logs-*-*

  ilm.enabled: false
  ilm.policy_name: logs

logging.level: warning

# External monitoring section
http:
  enabled: true
  port: 5066
  host: filebeat
monitoring.enabled: false
