filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

  processors:
  - decode_json_fields: # Decode JSON message into `msg` object
      fields: ["message"]
      target: "msg"
      overwrite_keys: true
      add_error_key: false
      when:
        not.has_fields: event.dataset # Do not process applications that will be processed by other modules

  - add_fields: # Add docker `event.dataset` field for container input
      target: event
      fields:
        dataset: docker
      when:
        and:
          - equals.input.type: container
          - not.has_fields: event.dataset # Do not process applications that will be processed by other modules

  - drop_fields: # Drop `message` when JSON decoded
      when:
        has_fields: ["msg"]
      fields: ["message"]
      ignore_missing: true

  - drop_fields: # Drop some useless fields
      fields:
        - "agent.ephemeral_id"
        - "docker.container.labels"
        - "msg.@timestamp"
      ignore_missing: true

  - drop_fields: # Drop `@timestamp` when `msg` have a time field
      fields: ["@timestamp"]
      when:
        has_fields: ["msg.time"]

  - rename:
      fields:
        - from: "msg.time" # Move time field to root
          to: "@timestamp"
        - from: "msg.msg" # Move message to follow ECS
          to: "message"
        - from: "msg.service" # Move service name to follow ECS
          to: "service.name"
        - from: "msg.trace.id" # Move trace.id to follow ECS
          to: "trace.id"
        - from: "msg.transaction.id" # Move transaction.id to follow ECS
          to: "transaction.id"
      ignore_missing: true
      fail_on_error: false

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  index: logs-elastic-internal
  ssl.ca_trusted_fingerprint: '${ELASTICSEARCH_CA_FINGERPRINT:}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

# Disable index setup
setup:
  kibana.host: kibana:5601
  dashboards.enabled: false
  dashboards.index: logs-elastic-internal

  template.enabled: false
  template.name: logs
  template.pattern: logs-*-*

  ilm.enabled: false
  ilm.policy_name: logs

logging.level: warning

# External monitoring section
http:
  enabled: true
  port: 5066
  host: filebeat
monitoring.enabled: false
