metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: system
    metricsets:
      - cpu             # CPU usage
      - load            # CPU load averages
      - memory          # Memory usage
      - network         # Network IO
      # - process         # Per process metrics
      - process_summary # Process summary
      - uptime          # System Uptime
      - socket_summary  # Socket summary
      - diskio         # Disk IO
      - filesystem     # File system usage for each mountpoint
      - fsstat         # File system summary metrics
    enabled: true
    period: 15s
    processes: ['.*']
    # Configure the mount point of the host’s filesystem for use in monitoring a host from within a container
    hostfs: /hostfs
    # Configure the metric types that are included by these metricsets.
    cpu.metrics:  ["percentages","normalized_percentages"]  # The other available option is ticks.
    core.metrics: ["percentages"]  # The other available option is ticks.

- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 15s
  enabled: true


- module: elasticsearch
  xpack.enabled: true
  period: 15s
  hosts: ["https://elastic:9200"]
  username: remote_monitoring_user
  password: '${MONITORING_PASSWORD}'
  ssl.ca_trusted_fingerprint: '${ELASTICSEARCH_CA_FINGERPRINT}'

- module: kibana
  xpack.enabled: true
  period: 15s
  hosts: http://kibana:5601
  username: "remote_monitoring_user"
  password: '${MONITORING_PASSWORD}'
  ssl.ca_trusted_fingerprint: '${ELASTICSEARCH_CA_FINGERPRINT}'

- module: beat
  xpack.enabled: true
  metricsets:
    - stats
    - state
  period: 15s
  hosts: ["http://localhost:5066", "http://filebeat:5066"]
  ssl.ca_trusted_fingerprint: '${ELASTICSEARCH_CA_FINGERPRINT}'

processors:
  - drop_fields:
      fields:
        - "agent.ephemeral_id"
        - "docker.container.labels"
      ignore_missing: true

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elastic:9200}'
  index: metrics-elastic-internal
  ssl.ca_trusted_fingerprint: '${ELASTICSEARCH_CA_FINGERPRINT:}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

# Disable index setup
setup:
  kibana.host: kibana:5601
  dashboards.enabled: false
  dashboards.index: metrics-elastic-internal

  template.enabled: false
  template.name: metrics
  template.pattern: metrics-*-*

  ilm.enabled: false
  ilm.policy_name: metrics

logging.level: warning

# External monitoring section
http:
  enabled: true
  port: 5066
monitoring.enabled: false
